#pragma once

#ifndef _MLTYPEDEF_
#define _MLTYPEDEF_

enum ML_RESULT
{
	ML_FAIL = 0,
	ML_VERSION_ERROR,
	ML_DATA_TYPE_ERROR,
	ML_MEM_ALLOC_ERROR,
	ML_MEM_FREE_ERROR,
	ML_MEM_SET_ERROR,
	ML_MEM_COPY_ERROR,
	ML_PARAM_ERROR,
	ML_DATA_ERROR,
	ML_CREATE_ERROR,
	ML_DESTROY_ERROR,
	ML_INIT_ERROR,
	ML_EXECUTE_ERROR,
	ML_FILE_HANDLE_ERROR,
	ML_FILE_OPEN_ERROR,
	ML_FILE_CREATE_ERROR,
	ML_FILE_CLOSE_ERROR,
	ML_FILE_READ_ERROR,
	ML_FILE_WRITE_ERROR,
	ML_FILE_SEEK_ERROR,
	ML_FILE_CONTENT_ERROR,
	ML_CUDA_GENERAL_ERROR,
	ML_CUDA_REGISTER_ERROR,
	ML_CUDA_UNREGISTER_ERROR,
	ML_CUDA_MAP_ERROR,
	ML_CUDA_UNMAP_ERROR,
	ML_GL_GENERAL_ERROR,
	ML_GL_WRITE_ERROR,
	ML_GL_READ_ERROR,
	ML_GL_TEXTURE_READ_ERROR,
	ML_GL_TEXTURE_WRITE_ERROR,
	ML_SUCCESS
};

#endif //_GVLTYPEDEF_